### ISSUE TITLE
Validation of requirement 10 from OGC API Tiles is not working properly

### ISSUE THREAD

**Issue by rkettelerij** [opengeospatial/ets-ogcapi-tiles10#13]
**Describe the bug**
Currently the testsuite assumes a `/collections` path is available. While the OGC API Tiles spec indicates that geospatial data resources (collections) are optional and only expected when (any of) the following conformance classes are specified:

- http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/geodata-tilesets
- http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/collections-selection

**To Reproduce**
1. Setup an OGC Tiles API with only a `/tiles` endpoint (next to the regular OGC Common endpoints)
2. Run test suite, observe that it fails with an error indicating `/collections` is expected (HTTP 404).

**Expected behavior**
First check `/conformance` to see if relevant classes are defined before testing `/collections`.

**Additional context**
The given error:
```
    <test started-at="2023-04-03T11:47:40Z" name="Tilesets List" finished-at="2023-04-03T11:47:40Z" duration-ms="59">
      <class name="org.opengis.cite.ogcapitiles10.tilesetslist.TilesetLlinks">
        <test-method is-config="true" signature="initCommonFixture(org.testng.ITestContext)[pri:0, instance:org.opengis.cite.ogcapitiles10.tilesetslist.TilesetLlinks@4b7dc788]" started-at="2023-04-03T13:47:40Z" name="initCommonFixture" finished-at="2023-04-03T13:47:40Z" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@3dc40ab9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initCommonFixture -->
        <test-method is-config="true" signature="clearMessages()[pri:0, instance:org.opengis.cite.ogcapitiles10.tilesetslist.TilesetLlinks@4b7dc788]" started-at="2023-04-03T13:47:40Z" name="clearMessages" finished-at="2023-04-03T13:47:40Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearMessages -->
        <test-method signature="validateTilesetsListResponse(org.opengis.cite.ogcapitiles10.openapi3.TestPoint)[pri:0, instance:org.opengis.cite.ogcapitiles10.tilesetslist.TilesetLlinks@4b7dc788]" started-at="2023-04-03T13:47:40Z" name="validateTilesetsListResponse" description="Implements Requirement 10 (/req/tilesets-list/tileset-links)" groups="tilesetsLists" data-provider="tilesetListsURIs" finished-at="2023-04-03T13:47:40Z" duration-ms="59" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Server URL: http://localhost:8080/ , Path: /collections, Replacements: {}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <200> but was <404>.
]]>
            </message>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
          <attributes>
            <attribute name="request">
              <![CDATA[Request method:	GET
Request URI:	http://localhost:8080/collections
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Headers:		Accept=application/json, application/javascript, text/javascript, text/json
Cookies:		<none>
Multiparts:		<none>
Body:			<none>
]]>
            </attribute> <!-- request -->
            <attribute name="response">
              <![CDATA[HTTP/1.1 404 Not Found
Content-Encoding: gzip
Content-Type: text/plain; charset=utf-8
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
Date: Mon, 03 Apr 2023 11:47:40 GMT
Content-Length: 43

404 page not found

]]>
            </attribute> <!-- response -->
          </attributes>
        </test-method> <!-- validateTilesetsListResponse -->
      </class> <!-- org.opengis.cite.ogcapitiles10.tilesetslist.TilesetLlinks -->
```

**Comment by rkettelerij** [comment]
Bump

**Comment by dstenger** [comment]
Thanks for reporting.
We will do further investigation.

**Comment by dstenger** [comment]
@rkettelerij Do you have a public API which we can use to reproduce the problem?
After having reviewed the spec, it seems that `/tiles` also seems to be optional. This must be considered for a potential fix.

**Comment by rkettelerij** [comment]
@dstenger yes, I have: https://api.pdok.nl/lv/bag/ogc/v1_0

**Comment by doublebyte1** [comment]
@rkettelerij I think we found a similar issue. The ets seems to be expecting dataset tilesets, when a server may only offer collection tilesets.

https://github.com/opengeospatial/ets-ogcapi-tiles10/issues/28

**Comment by jerstlouis** [comment]
Clarification:
- The existence of `/tiles` at the root of the API is optional for all requirement classes, though it is a "common" path for the only or "data" tilesets. The client / ETS should either be provided the URL to an individual tileset directly when testing "TileSet" conformance class, the list of tilesets when testling "TileSet List", or discover those `.../tiles` URLs from links with relation `tilesets-*` (vector, map, coverage...) from an OGC API collection description and/or landing page.
- "The TileSets list conformance class does require that paths listing tilesets end with …​/tiles." ([Requirement 9A](https://docs.ogc.org/is/20-057/20-057.html#toc36), though this could be e.g. `/map/tiles` in the case of map tilesets)
- Only http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/geodata-tilesets requires the presence of `/collections`. Potentially Collection Selection requirement class could be used with an API that does not implement OGC API - Common Part 1 or 2 at all, but still providing a way to pick layers to include in the response if they support the `collections=` parameter (it would need its own mechanism in this case to list available collections). So while the ETS can use `/collections` if it exists to list available layers when testing DataSet TileSets + Collection Selection, it is not a requirement (perhaps it could allow the ETS user to manually provide layers to include in the UI). This is not clear in the published document because the `(optional)` tag on the dependency to Common - Part 2 "Collections" which is present in the [source ASCIIDoc](https://github.com/opengeospatial/ogcapi-tiles/blob/master/core/standard/requirements/requirements_class_collections-selection.adoc) is not reflected in the HTML and PDF. The intent was for this dependency to be optional, meaning that the ETS / client can use `/collections` to list available collections if available.

**Comment by dstenger** [comment]
Thank you for the clarification.

We will do further discussion in the CITE team as stated in https://github.com/opengeospatial/ets-ogcapi-tiles10/issues/28#issuecomment-2231515950.
