### ISSUE TITLE
Validation of requirement 10

### ISSUE THREAD

**Issue by doublebyte1** [opengeospatial/ets-ogcapi-tiles10#28]
**Describe the bug**
The ETS  expects Dataset Tilesets, which [according to the spec are not a core requirement](https://docs.ogc.org/is/20-057/20-057.html#toc40). See the discussion [here](https://github.com/opengeospatial/ogcapi-tiles/issues/169). 

**To Reproduce**
Run the tests for a server that does not implement dataset tilesets:

https://maps.gnosis.earth/ogcapi/?f=json
https://demo.pygeoapi.io/master/?f=json

The ets produces an error.

**Expected behavior**
These servers do not claim to support dataset tilesets in the conformance declaration, and should not be tested for it. Instead they support collection tilesets.

**Additional context**
[This](https://github.com/opengeospatial/ets-ogcapi-tiles10/issues/13) issue is also related to the fact that a test that is not mandatory is being run.

**Comment by dstenger** [comment]
Thank you for reporting.
Indeed, we already discussed this topic in the CITE team because a similar issue was reported in https://github.com/opengeospatial/ets-ogcapi-tiles10/issues/13 as described above.

Our conclusion was that the test suite must be improved:
* either the tests are skipped/removed/made optional
* or further input parameters are added
* or a precondition is defined for the ETS making an optional requirement mandatory for the test suite

We will do further discussion in the CITE team.

**Comment by tomkralidis** [comment]
Looks like this has been addressed in #29, thanks!  Is there a beta release anytime soon so we can test?  Or a way to test locally (having Docker, not Maven)?

**Comment by dstenger** [comment]
Yes, we will create a new [Beta release](https://cite.ogc.org/te2/) at the end of this or next month.
Then, you can also download a Docker Image from DockerHub:
* https://hub.docker.com/r/ogccite/teamengine-beta
* https://hub.docker.com/r/ogccite/ets-ogcapi-tiles10

Right now, you can, of course, also test the fix. But then you have to build the test suite which requires Maven. If you need further instructions for that, please contact me.

**Comment by tomkralidis** [comment]
Thanks @dstenger.  fwiw I was able to test locally using the [local build instructions](https://github.com/opengeospatial/ets-ogcapi-tiles10/blob/master/src/site/asciidoc/how-to-run-the-tests.adoc#3-docker-while-at-alpha-stage) (ended up installing Maven).
